### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by mTrax-** [z720/gandi-ddns#2]
Hi,

I have tried a few things to configure the config.json file but without success. The api-key is not accepted (while it works when I export it).
Any advice ?

Thanks,
G.

**Comment by z720** [comment]
Do you have an example?
What kind of error do you get?
(Don’t post you’re actual api key)

**Comment by mTrax-** [comment]
I kept it simple : 
For the root record :
`{
        "api-key": "GANDI_KEY",
        "domain": "domain.tld",
        "record": "{@,*}"
}`
And for a subdomain (another folder) :
`{
        "api-key": "GANDI_KEY",
        "domain": "domain.tld",
        "record": "home"
}`

When I do npm start, I get : 
`> ddns-gandi@1.0.0 start /opt/gandi-ddns/domain.tld
> node index.js

Couldn't initiate process:  Gandi Authorization declined, check GANDI_API_KEY`

When I use the same command without the config.json:
`export GANDI_API_KEY=GANDI_KEY && cd /opt/gandi-ddns/domain.tld/ && /usr/bin/npm start madb.fr {@,*}`

I have a successful : 
`> ddns-gandi@1.0.0 start /opt/gandi-ddns/domain.tlk
> node index.js "domain.tld" "@" "config.js" "config.json" "Dockerfile" "gandi.js" "index.js" "node_modules" "package.json" "package-lock.json" "README.md" "secrets.js"

Start monitoring IP  @ domain.tld IP_ADDRESS`

Thx for looking !

**Comment by z720** [comment]
Should be fixed with version 1.0.1

**Comment by mTrax-** [comment]
It works well, thx !
